Repository Kernel360/KDEV3_monicar_BE, pull requests merged in 2024-12, with the labels that each got.

#2 [build] 공통모듈세팅
  build.gradle
  monicar-collector/build.gradle
  monicar-collector/src/main/java/org/collector/CollectorApplication.java
  monicar-common/.gitattributes
  monicar-common/.gitignore
  monicar-common/build.gradle
  monicar-common/gradle/wrapper/gradle-wrapper.jar
  monicar-common/gradle/wrapper/gradle-wrapper.properties
  monicar-common/gradlew
  monicar-common/gradlew.bat
  monicar-common/settings.gradle
  monicar-common/src/main/java/org/common/TestBean.java
  monicar-common/src/main/resources/application.properties
  monicar-emulator/build.gradle
  monicar-emulator/src/main/java/org/emulator/EmulatorApplication.java
  settings.gradle
Labels: setting

#5 [feat] 주기정보 요청값 및 공통 응답값 세팅
  monicar-common/src/main/java/org/common/dto/CListRequest.java
  monicar-common/src/main/java/org/common/dto/CommonResponse.java
  monicar-common/src/main/java/org/common/dto/CycleInfoRequest.java
Labels: ✨ Feat

#8 [feat] 에뮬레이터-로컬-저장소-설계-및-구현2
  monicar-emulator/src/main/java/org/emulator/application/EmulatorRepository.java
  monicar-emulator/src/main/java/org/emulator/application/dto/CtrListDto.java
  monicar-emulator/src/main/java/org/emulator/application/dto/GeoListDto.java
  monicar-emulator/src/main/java/org/emulator/application/dto/OnOffDataDto.java
  monicar-emulator/src/main/java/org/emulator/infrastructure/ControlData.java
  monicar-emulator/src/main/java/org/emulator/infrastructure/EmulatorConstant.java
  monicar-emulator/src/main/java/org/emulator/infrastructure/GeoPointData.java
  monicar-emulator/src/main/java/org/emulator/infrastructure/InMemoryStore.java
  monicar-emulator/src/main/java/org/emulator/infrastructure/VehicleEventData.java
  monicar-emulator/src/main/java/org/emulator/infrastructure/VehicleGlobalData.java
Labels: ✨ Feat

#13 [chore] 빌드 의존성 문제 해결
  build.gradle
Labels: 🔧 Chore

#15 이슈 템플릿 추가
  .github/ISSUE_TEMPLATE/chore-issue-template.md
  .github/ISSUE_TEMPLATE/etc-issue-template.md
  .github/ISSUE_TEMPLATE/feature-issue-template.md
  .github/ISSUE_TEMPLATE/fix-issue-template.md
Labels: 📝 Docs

#20 PR 템플릿 추가 close#17
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: 📝 Docs

#21 [refactor] gps상태 필드 Enum으로 관리하도록 변경
  monicar-common/src/main/java/org/common/dto/CListRequest.java
  monicar-common/src/main/java/org/common/dto/GCD.java
Labels: ♻️ Refactor, priority

#24 feat: 관제 센터 공통 응답 포맷 클래스 추가
  monicar-control-center/src/main/java/org/controlcenter/dto/BaseResponse.java
  monicar-control-center/src/main/java/org/controlcenter/dto/ErrorCode.java
  monicar-control-center/src/main/java/org/controlcenter/dto/SuccessCode.java
Labels: ✨ Feat

#27 refactor: 애뮬레이터 패키지 구조화
  monicar-emulator/src/main/java/org/emulator/application/EmulatorRepository.java
  monicar-emulator/src/main/java/org/emulator/application/VehicleService.java
  monicar-emulator/src/main/java/org/emulator/application/port/EmulatorRepository.java
  monicar-emulator/src/main/java/org/emulator/application/port/LocationEventPublisher.java
  monicar-emulator/src/main/java/org/emulator/application/port/LocationReceiver.java
  monicar-emulator/src/main/java/org/emulator/application/port/VehicleCommandSender.java
  monicar-emulator/src/main/java/org/emulator/domain/ControlData.java
  monicar-emulator/src/main/java/org/emulator/domain/EmulatorInfo.java
  monicar-emulator/src/main/java/org/emulator/domain/GeoPointData.java
  monicar-emulator/src/main/java/org/emulator/domain/VehicleGlobalData.java
  monicar-emulator/src/main/java/org/emulator/domain/dto/CtrListDto.java
  monicar-emulator/src/main/java/org/emulator/domain/dto/GeoListDto.java
  monicar-emulator/src/main/java/org/emulator/infrastructure/ControlData.java
  monicar-emulator/src/main/java/org/emulator/infrastructure/EmulatorConstant.java
  monicar-emulator/src/main/java/org/emulator/infrastructure/InMemoryStore.java
  monicar-emulator/src/main/java/org/emulator/infrastructure/VehicleEventData.java
  monicar-emulator/src/main/java/org/emulator/infrastructure/external/RestClientVehicleCommandSender.java
  monicar-emulator/src/main/java/org/emulator/infrastructure/external/command/OffCommand.java
  monicar-emulator/src/main/java/org/emulator/infrastructure/external/command/OnCommand.java
  monicar-emulator/src/main/java/org/emulator/infrastructure/file/FileLocationReceiver.java
  monicar-emulator/src/main/java/org/emulator/infrastructure/messaging/KafkaLocationEventPublisher.java
  monicar-emulator/src/main/java/org/emulator/infrastructure/messaging/event/VehicleEvent.java
  monicar-emulator/src/main/java/org/emulator/infrastructure/repository/InMemoryEmulatorRepository.java
  monicar-emulator/src/main/java/org/emulator/presentation/VehicleController.java
Labels: ♻️ Refactor

#28 style: 코드 포맷팅 적용
  .editorconfig
Labels: 💄 Style

#29 [feat] 시동 on 요청
  monicar-emulator/build.gradle
  monicar-emulator/src/main/java/org/emulator/application/VehicleService.java
  monicar-emulator/src/main/java/org/emulator/application/port/EmulatorRepository.java
  monicar-emulator/src/main/java/org/emulator/application/port/VehicleCommandSender.java
  monicar-emulator/src/main/java/org/emulator/common/HeaderName.java
  monicar-emulator/src/main/java/org/emulator/common/HeaderUtils.java
  monicar-emulator/src/main/java/org/emulator/common/RequestUtils.java
  monicar-emulator/src/main/java/org/emulator/common/VehicleConstant.java
  monicar-emulator/src/main/java/org/emulator/domain/ControlData.java
  monicar-emulator/src/main/java/org/emulator/domain/ControlInfo.java
  monicar-emulator/src/main/java/org/emulator/domain/EmulatorInfo.java
  monicar-emulator/src/main/java/org/emulator/domain/GeoPoint.java
  monicar-emulator/src/main/java/org/emulator/domain/GpsStatus.java
  monicar-emulator/src/main/java/org/emulator/domain/OffInfo.java
  monicar-emulator/src/main/java/org/emulator/domain/OnInfo.java
  monicar-emulator/src/main/java/org/emulator/domain/VehicleGlobalData.java
  monicar-emulator/src/main/java/org/emulator/domain/VehicleInfo.java
  monicar-emulator/src/main/java/org/emulator/domain/dto/GeoListDto.java
  monicar-emulator/src/main/java/org/emulator/infrastructure/external/RestClientFactory.java
  monicar-emulator/src/main/java/org/emulator/infrastructure/external/RestClientService.java
  monicar-emulator/src/main/java/org/emulator/infrastructure/external/RestClientVehicleCommandSender.java
  monicar-emulator/src/main/java/org/emulator/infrastructure/external/UrlPathEnum.java
  monicar-emulator/src/main/java/org/emulator/infrastructure/external/command/CtrList.java
  monicar-emulator/src/main/java/org/emulator/infrastructure/external/command/GeoList.java
  monicar-emulator/src/main/java/org/emulator/infrastructure/external/command/OnCommand.java
  monicar-emulator/src/main/java/org/emulator/infrastructure/messaging/event/VehicleEvent.java
  monicar-emulator/src/main/java/org/emulator/infrastructure/repository/InMemoryEmulatorRepository.java
  monicar-emulator/src/main/java/org/emulator/presentation/VehicleController.java
  monicar-emulator/src/main/resources/application.yml
  monicar-emulator/src/test/java/org/emulator/application/port/VehicleCommandSenderTest.java
  monicar-emulator/test.http
Labels: ✨ Feat

#36 feat: gps 탐지 센서 스레드 구현
  monicar-emulator/src/main/java/org/emulator/EmulatorApplication.java
  monicar-emulator/src/main/java/org/emulator/config/AsyncConfig.java
  monicar-emulator/src/main/java/org/emulator/config/ScheduleConfig.java
  monicar-emulator/src/main/java/org/emulator/device/application/VehicleService.java
  monicar-emulator/src/main/java/org/emulator/device/application/port/EmulatorRepository.java
  monicar-emulator/src/main/java/org/emulator/device/domain/GeoPoint.java
  monicar-emulator/src/main/java/org/emulator/device/domain/VehicleInfo.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/external/RestClientFactory.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/external/RestClientService.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/external/RestClientVehicleCommandSender.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/external/command/CtrList.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/external/command/GeoList.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/external/command/OffCommand.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/external/command/OnCommand.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/repository/InMemoryEmulatorRepository.java
  monicar-emulator/src/main/java/org/emulator/device/presentation/VehicleController.java
  monicar-emulator/src/main/java/org/emulator/sensor/GpsDetector.java
  monicar-emulator/src/main/java/org/emulator/sensor/GpsSensor.java
  monicar-emulator/src/main/java/org/emulator/sensor/SensorDetector.java
Labels: ✨ Feat

#34 [feat] 주기 정보 저장 및 예외처리 작업
  monicar-collector/build.gradle
  monicar-collector/src/main/java/org/collector/application/CycleInfoService.java
  monicar-collector/src/main/java/org/collector/common/annotation/CycleCount.java
  monicar-collector/src/main/java/org/collector/common/exception/CustomException.java
  monicar-collector/src/main/java/org/collector/common/exception/GlobalExceptionHandler.java
  monicar-collector/src/main/java/org/collector/common/response/CommonResponse.java
  monicar-collector/src/main/java/org/collector/common/response/ResponseCode.java
  monicar-collector/src/main/java/org/collector/common/validation/CycleCountValidator.java
  monicar-collector/src/main/java/org/collector/domain/CycleInfo.java
  monicar-collector/src/main/java/org/collector/infrastructure/repository/CycleInfoRepository.java
  monicar-collector/src/main/java/org/collector/presentation/CycleInfoController.java
  monicar-collector/src/main/java/org/collector/presentation/dto/CListRequest.java
  monicar-collector/src/main/java/org/collector/presentation/dto/CycleInfoRequest.java
  monicar-collector/src/main/java/org/collector/presentation/dto/GCD.java
  monicar-collector/src/main/resources/application.yml
  monicar-common/src/main/java/org/common/dto/ResponseCode.java
Labels: ✨ Feat

#41 feat: gps 신호를 queue 에 넣는 기능 구현
  monicar-emulator/src/main/java/org/emulator/pipe/Gps.java
  monicar-emulator/src/main/java/org/emulator/pipe/GpsPipeQueue.java
  monicar-emulator/src/main/java/org/emulator/sensor/GpsDetector.java
Labels: ✨ Feat
