Repository Kernel360/KDEV3_monicar_BE, pull requests merged in 2025-02, with the labels that each got.

#241 feature: 시간별 운행기록 API 구현
  monicar-control-center/src/main/java/org/controlcenter/common/exception/GlobalExceptionHandler.java
  monicar-control-center/src/main/java/org/controlcenter/common/response/code/ErrorCode.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/DrivingLogService.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/port/DrivingLogRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/HourlyDrivingLogs.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/DrivingLogJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/DrivingLogController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/swagger/DrivingLogApi.java
  monicar-control-center/src/main/resources/data/init-data.sql
Labels: 🐛 Fix, ✨ Feat, 🔧 Chore

#220 refactor: 파티션 여러개 분리함에 따라 필요한 부분 수정
  monicar-collector/src/main/java/org/collector/config/KafkaConfig.java
  monicar-collector/src/main/java/org/collector/config/PartitionFinder.java
  monicar-collector/src/main/java/org/collector/consumer/CycleInfoConsumer.java
Labels: ♻️ Refactor

#238 fix: 모니터링 수정
  monicar-emulator/src/main/resources/application.yml
  monicar-emulator/src/main/resources/logback-spring.xml
  monicar-event-hub/Dockerfile
  monicar-event-hub/src/main/resources/application-dev.yml
  monicar-event-hub/src/main/resources/logback-spring.xml
  monicar-event-hub/src/main/resources/static/favicon.ico
Labels: 🔧 Chore

#242 feat: gpx 파일 로드하기
  monicar-emulator/src/main/java/org/emulator/device/common/response/ErrorCode.java
  monicar-emulator/src/main/java/org/emulator/sensor/GpsDetector.java
  monicar-emulator/src/main/java/org/emulator/sensor/GpxFileParser.java
  monicar-emulator/src/main/java/org/emulator/sensor/dto/GpsListCircular.java
  monicar-emulator/src/main/resources/application.yml
  monicar-emulator/src/main/resources/gpx/Gangnam-to-Pyeongchang-formatted.gpx
Labels: ✨ Feat

#252 fix: 환경에 따른 쿠키 도메인이 변경되도록 수정
  monicar-control-center/src/main/java/org/controlcenter/common/util/CookieUtil.java
  monicar-control-center/src/main/resources/application-dev.yml
  monicar-control-center/src/main/resources/application-prod.yml
Labels: 🐛 Fix

#257 feat: 임시 회원가입 기능(간단한 회원가입)
  monicar-control-center/src/main/java/org/controlcenter/common/response/code/ErrorCode.java
  monicar-control-center/src/main/java/org/controlcenter/common/security/JWTFilter.java
  monicar-control-center/src/main/java/org/controlcenter/company/application/ManagerService.java
  monicar-control-center/src/main/java/org/controlcenter/company/domain/Manager.java
  monicar-control-center/src/main/java/org/controlcenter/company/infrastructure/jpa/ManagerJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/company/presentation/ManagerController.java
  monicar-control-center/src/main/java/org/controlcenter/company/presentation/dto/SignUpRequest.java
  monicar-control-center/src/main/resources/schema/init-schema.sql
Labels: ✨ Feat, priority

#260 chore: 한국시간으로 저장이 되지 않는 문제 수정
  monicar-control-center/src/main/java/org/controlcenter/common/response/code/ErrorCode.java
  monicar-control-center/src/main/resources/application-dev.yml
  monicar-control-center/src/main/resources/application-prod.yml
Labels: 🔧 Chore

#263 feat: 에뮬레이터 시동 off 요청
  monicar-control-center/src/main/resources/logback-spring-dev.xml
  monicar-emulator/src/main/java/org/emulator/device/application/VehicleService.java
  monicar-emulator/src/main/java/org/emulator/device/application/port/EmulatorRepository.java
  monicar-emulator/src/main/java/org/emulator/device/application/port/VehicleEventSender.java
  monicar-emulator/src/main/java/org/emulator/device/domain/OffInfo.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/entity/VehicleEntity.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/external/VehicleEventRestClient.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/external/command/OffCommand.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/external/command/OnCommand.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/repository/InMemoryEmulatorRepository.java
  monicar-emulator/src/main/java/org/emulator/device/presentation/VehicleApiController.java
  monicar-emulator/src/main/java/org/emulator/sensor/GpsTracker.java
  monicar-emulator/src/main/resources/application.yml
  monicar-emulator/src/main/resources/gpx/Gangnam-to-Pyeongchang-formatted.gpx
  monicar-emulator/src/main/resources/gpx/suwon-daejon-gumi-optimized.gpx
  monicar-emulator/src/main/resources/logback-spring-dev.xml
  monicar-emulator/src/test/api_test.http
Labels: 🐛 Fix, ✨ Feat, 🔧 Chore

#266 feat: 개별차량 조회 페이지네이션
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/VehicleQueryRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/mybatis/MyBatisVehicleInfoMapper.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/VehicleController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/swagger/VehicleApi.java
Labels: ✨ Feat

#270 fix: 기존 PageResponse를 포함하여 반환하도록 수정
  monicar-control-center/src/main/java/org/controlcenter/common/response/PageResponse.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/VehicleQueryRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/mybatis/MyBatisVehicleInfoMapper.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/VehicleController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/swagger/VehicleApi.java
Labels: 🐛 Fix

#273 feautre: 지도 클러스터링 API 구현
  monicar-control-center/src/main/java/org/controlcenter/common/response/code/ErrorCode.java
  monicar-control-center/src/main/java/org/controlcenter/company/presentation/AuthController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/ClusterService.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/Cluster.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/VehicleInformationJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/entity/VehicleInformationEntity.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/VehicleController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/dto/ClusterResponse.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/swagger/VehicleApi.java
  monicar-control-center/src/main/resources/data/init-data.sql
  monicar-control-center/src/main/resources/schema/init-schema.sql
Labels: ✨ Feat

#280 feature: 클러스터링 상세 조회 API
  monicar-control-center/src/main/java/org/controlcenter/common/security/JWTFilter.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/ClusterService.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/ClusterDetail.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/VehicleInformationJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/VehicleController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/swagger/VehicleApi.java
  monicar-control-center/src/main/resources/data/init-data.sql
Labels: ✨ Feat

#282 feature: 차량 고유 아이디로 차량 정보 조회 API
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/VehicleService.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/VehicleController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/swagger/VehicleApi.java
Labels: ✨ Feat

#284 feature: 차량 등록 시 차량 번호 중복확인 API
  monicar-control-center/src/main/java/org/controlcenter/common/response/code/ErrorCode.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/DrivingLogService.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/VehicleController.java
Labels: ✨ Feat

#287 fix: 차량 상세 조회 시 상태값 추가
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/DrivingLogService.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/SpecificVehicleInformation.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/VehicleHeaderInfo.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/DrivingLogJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/dto/DrivingLogResponse.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/dto/VehicleDrivingLogDetailsResponse.java
Labels: 🐛 Fix

#293 feature: 지도 상세 리스트 조회 시 차량 상태 포함하여 반환
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/ClusterDetail.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/VehicleInformationJpaRepository.java
  monicar-control-center/src/main/resources/application-dev.yml
  monicar-control-center/src/main/resources/application-prod.yml
Labels: ✨ Feat

#296 feat: 차량 정보의 상태(운행, 미운행) update 로직
  monicar-control-center/src/test/resources/application-test.yml
  monicar-event-hub/src/main/java/org/eventhub/application/VehicleService.java
  monicar-event-hub/src/main/java/org/eventhub/application/port/VehicleRepository.java
  monicar-event-hub/src/main/java/org/eventhub/infrastructure/repository/VehicleInformationRepositoryAdapter.java
  monicar-event-hub/src/main/java/org/eventhub/infrastructure/repository/jpa/entity/VehicleInformationEntity.java
  monicar-event-hub/src/main/java/org/eventhub/presentation/OnOffController.java
Labels: ✨ Feat

#294 feat: 차량 정보를 통해 운행 중, 미운행 중 판단하는 기능 구현
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/VehicleService.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/VehicleInformation.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/VehicleController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/swagger/VehicleApi.java
Labels: ✨ Feat

#299 feat: 주기 정보에서 안쓰이는 sum 지우기
  monicar-emulator/src/main/java/org/emulator/sensor/GpsTracker.java
  monicar-event-hub/src/main/java/org/eventhub/domain/CycleInfo.java
  monicar-event-hub/src/main/java/org/eventhub/infrastructure/messaging/command/CycleInfoCommand.java
Labels: 🐛 Fix

#298 fix: mdn컬럼에 unique속성 추가
  monicar-collector/src/main/java/org/collector/domain/VehicleInformation.java
  monicar-control-center/src/main/resources/schema/init-schema.sql
Labels: 🐛 Fix, priority

#303 fix: 차량 등록시 MDN GUID 메서드 구현
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/VehicleInformation.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/VehicleController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/swagger/VehicleApi.java
Labels: 🐛 Fix

#304 feature: 차량 검색 자동완성 API 구현
  .github/workflows/cicd.yml
  monicar-control-center/build.gradle
  monicar-control-center/src/main/java/org/controlcenter/config/ElasticsearchConfig.java
  monicar-control-center/src/main/java/org/controlcenter/config/VehicleMigrationRunner.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/VehicleInformationMigrationService.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/VehicleSearchService.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/VehicleService.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/elasticsearch/document/VehicleInformationDocument.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/elasticsearch/repository/VehicleInformationElasticsearchRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/elasticsearch/repository/VehicleSearchQueryRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/entity/VehicleInformationEntity.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/VehicleController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/dto/SimpleVehicleInformationResponse.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/swagger/VehicleApi.java
  monicar-control-center/src/main/resources/application-dev.yml
  monicar-control-center/src/main/resources/application-prod.yml
  monicar-control-center/src/main/resources/elasticsearch/vehicle_information_mappings.json
  monicar-control-center/src/main/resources/elasticsearch/vehicle_information_settings.json
  monicar-control-center/src/test/resources/application-test.yml
Labels: ✨ Feat

#309 refactor: 지연로딩 설정 및 예외처리 제거
  monicar-collector/src/main/java/org/collector/common/constant/CycleInfoSize.java
  monicar-collector/src/main/java/org/collector/consumer/CycleInfoConsumer.java
  monicar-collector/src/main/java/org/collector/domain/CycleInfo.java
  monicar-collector/src/main/java/org/collector/domain/VehicleInformation.java
  monicar-collector/src/main/java/org/collector/presentation/CycleInfoController.java
Labels: ♻️ Refactor

#310 feature: 점검 알림 SSE 및 API 구현
  monicar-control-center/src/main/java/org/controlcenter/ControlCenterApplication.java
  monicar-control-center/src/main/java/org/controlcenter/alarm/application/AlarmService.java
  monicar-control-center/src/main/java/org/controlcenter/alarm/application/port/AlarmRepository.java
  monicar-control-center/src/main/java/org/controlcenter/alarm/domain/Alarm.java
  monicar-control-center/src/main/java/org/controlcenter/alarm/domain/AlarmCreate.java
  monicar-control-center/src/main/java/org/controlcenter/alarm/domain/AlarmInfo.java
  monicar-control-center/src/main/java/org/controlcenter/alarm/domain/AlarmStatus.java
  monicar-control-center/src/main/java/org/controlcenter/alarm/domain/SendAlarm.java
  monicar-control-center/src/main/java/org/controlcenter/alarm/infrastructure/jpa/AlarmJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/alarm/infrastructure/jpa/AlarmRepositoryAdapter.java
  monicar-control-center/src/main/java/org/controlcenter/alarm/infrastructure/jpa/entity/AlarmEntity.java
  monicar-control-center/src/main/java/org/controlcenter/alarm/presentation/AlarmController.java
  monicar-control-center/src/main/java/org/controlcenter/alarm/presentation/dto/AlarmResponse.java
  monicar-control-center/src/main/java/org/controlcenter/alarm/presentation/swagger/AlarmApi.java
  monicar-control-center/src/main/java/org/controlcenter/common/scheduler/Scheduler.java
  monicar-control-center/src/main/java/org/controlcenter/common/util/JWTTokenValidator.java
  monicar-control-center/src/main/java/org/controlcenter/config/SecurityConfig.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/swagger/VehicleApi.java
  monicar-control-center/src/main/resources/application-dev.yml
  monicar-control-center/src/main/resources/application-prod.yml
  monicar-control-center/src/main/resources/data/init-data.sql
  monicar-control-center/src/main/resources/schema/init-schema.sql
  monicar-control-center/src/test/java/org/controlcenter/jpa/JpaTest.java
  monicar-control-center/src/test/resources/application-test.yml
Labels: ✨ Feat

#315 fix: 운행일지 상세조회 업무용 사용거리, 업무사용비율 로직 수정
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/DrivingLogSummary.java
Labels: 🐛 Fix

#316 fix: 시간별 운행내역 페이지 부분 차량번호 추가
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/DrivingLogService.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/DrivingLogController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/dto/HourlyDrivingLogsResponse.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/swagger/DrivingLogApi.java
Labels: 🐛 Fix

#317 feature: 주행거리 많은 순 랭킹 API 구현
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/VehicleInformationJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/VehicleController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/dto/SimpleRankResponse.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/swagger/VehicleApi.java
Labels: ✨ Feat

#319 fix: 일별 운행내역 페이지 부분 차량번호 추가
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/DrivingLogService.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/DrivingLogController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/dto/DailyDrivingLogsResponse.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/dto/HourlyDrivingLogsResponse.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/swagger/DrivingLogApi.java
Labels: 🐛 Fix

#320 fix: 차량 정보 조회 api 수정
  monicar-control-center/src/main/java/org/controlcenter/alarm/application/AlarmService.java
  monicar-control-center/src/main/java/org/controlcenter/alarm/domain/AlarmStatus.java
  monicar-control-center/src/main/java/org/controlcenter/common/response/code/ErrorCode.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/VehicleInformation.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/VehicleQueryRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/mybatis/MyBatisVehicleInfoMapper.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/VehicleController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/dto/VehicleModalResponse.java
  monicar-control-center/src/test/java/org/controlcenter/jpa/JpaTest.java
Labels: 🐛 Fix

#327 chore: SSE 알람이 전송되지 않는 문제 확인용 로그
  monicar-control-center/src/main/java/org/controlcenter/alarm/application/AlarmService.java
Labels: 🔧 Chore

#328 fix: 점검 알람 컨트롤러 미디어 타입 명시적 지정
  monicar-control-center/src/main/java/org/controlcenter/alarm/presentation/AlarmController.java
Labels: 🐛 Fix

#329 fix: 메세지 전체 전송 로그 상세하게 출력되도록 추가
  monicar-control-center/src/main/java/org/controlcenter/alarm/application/AlarmService.java
  monicar-control-center/src/main/java/org/controlcenter/alarm/presentation/AlarmController.java
Labels: 🐛 Fix

#330 fix: 점검 알람 롤백 처리
  monicar-control-center/src/main/java/org/controlcenter/alarm/application/AlarmService.java
  monicar-control-center/src/main/java/org/controlcenter/alarm/presentation/AlarmController.java
Labels: 🐛 Fix

#331 fix: X-Accel-Buffering을 사용하여 SSE 응답만 버퍼링하지 않도록 수정
  monicar-control-center/src/main/java/org/controlcenter/alarm/presentation/AlarmController.java
  monicar-control-center/src/main/java/org/controlcenter/alarm/presentation/swagger/AlarmApi.java
Labels: 🐛 Fix

#323 fix: 에뮬레이터가 event hub 인스턴스에 on off 요청시 실패 응답
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/util/HeaderUtils.java
Labels: 🐛 Fix

#325 feature: 점검 상태별 개수 API
  monicar-control-center/src/main/java/org/controlcenter/alarm/application/AlarmService.java
  monicar-control-center/src/main/java/org/controlcenter/alarm/domain/AlarmStatusStats.java
  monicar-control-center/src/main/java/org/controlcenter/alarm/domain/SendAlarm.java
  monicar-control-center/src/main/java/org/controlcenter/alarm/infrastructure/jpa/AlarmJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/alarm/presentation/AlarmController.java
  monicar-control-center/src/main/java/org/controlcenter/alarm/presentation/dto/AlarmStatusStatsResponse.java
  monicar-control-center/src/main/java/org/controlcenter/common/scheduler/Scheduler.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/cluster/ClusterCreateCommand.java
Labels: ✨ Feat

#335 fix: PropertyConfig dev에서만 쓰도록 어노테이션 추가
  monicar-event-hub/src/main/java/org/eventhub/config/PropertyConfig.java
Labels: 🐛 Fix

#336 fix: actuator 의존성 제거
  monicar-event-hub/build.gradle
  monicar-event-hub/src/main/resources/application-dev.yml
Labels: 🔧 Chore

#339 fix: 점검 상태별 통계 응답 시 상태값으로 반환하도록 수정
  monicar-control-center/src/main/java/org/controlcenter/alarm/application/AlarmService.java
  monicar-control-center/src/main/java/org/controlcenter/alarm/domain/AlarmStatusStats.java
  monicar-control-center/src/main/java/org/controlcenter/alarm/presentation/dto/AlarmStatusStatsResponse.java
Labels: 🐛 Fix

#342 fix: 점검 목록 조회 시 사용자가 확인하지 않은 목록만 반환하도록 수정
  monicar-control-center/src/main/java/org/controlcenter/alarm/infrastructure/jpa/AlarmJpaRepository.java
Labels: 🐛 Fix

#343 fix: 예외 처리로 원래 트랜잭션에 영향 없도록 하기
  monicar-event-hub/src/main/java/org/eventhub/application/AlarmService.java
  monicar-event-hub/src/main/java/org/eventhub/application/port/AlarmRepository.java
  monicar-event-hub/src/main/java/org/eventhub/infrastructure/repository/AlarmRepositoryAdapter.java
Labels: 🐛 Fix

#344 fix: 알림 데이터 저장 에러 수정
  monicar-event-hub/src/main/java/org/eventhub/application/AlarmService.java
  monicar-event-hub/src/main/java/org/eventhub/application/port/AlarmRepository.java
  monicar-event-hub/src/main/java/org/eventhub/infrastructure/repository/AlarmRepositoryAdapter.java
Labels: 🐛 Fix

#348 fix: 지도 상태별 차량 대수 조회 문제 수정
  monicar-control-center/src/main/java/org/controlcenter/common/security/JWTFilter.java
  monicar-control-center/src/main/java/org/controlcenter/common/util/JWTTokenValidator.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/mybatis/MyBatisVehicleInfoMapper.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/dto/SimpleVehicleInformationResponse.java
Labels: 🐛 Fix

#349 docs: 프로젝트 소개 및 Trouble Shooting 문서화
  README.md
  img/ERD.png
  img/Kafa도입이유.md
  img/login-page.png
  img/suhyun.png
  img/난아.png
  img/병훈.png
  img/부하테스트.md
  img/수현.png
  img/아키텍처.png
  img/지윤.png
  img/혁준.png
  img/흐름.png
Labels: 📝 Docs

#353 docs: readme 업데이트
  README.md
  img/Kafa도입이유.md
  img/부하테스트.md
Labels: 📝 Docs

#354 chore: init data sql 수정
  .github/workflows/cicd.yml
  monicar-control-center/src/main/resources/data/init-data.sql
  monicar-emulator/simulation/start-one-container.sh
  monicar-emulator/src/main/resources/gpx/gyeongju-to-seoul_no_ns.gpx
  monicar-emulator/src/main/resources/gpx/seoul-to-gyeongju_formatted.gpx
Labels: 🔧 Chore

#356 fix: 알람 상태별 개수 통계 반환 방식 변경
  monicar-control-center/src/main/java/org/controlcenter/alarm/application/AlarmService.java
  monicar-control-center/src/main/java/org/controlcenter/alarm/domain/AlarmStatusStats.java
  monicar-control-center/src/main/java/org/controlcenter/alarm/infrastructure/jpa/AlarmJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/alarm/presentation/AlarmController.java
  monicar-control-center/src/main/java/org/controlcenter/alarm/presentation/dto/AlarmStatusStatsResponse.java
Labels: 🐛 Fix

#359 docs: Readme Update
  README.md
Labels: 📝 Docs

#360 docs: README.md 업데이트
  README.md
  monicar-control-center/src/main/java/org/controlcenter/common/scheduler/Scheduler.java
Labels: 📝 Docs

#362 Chore: 사용하지않는 모듈 제거
  img/아키텍처.png
  monicar-track-alert/Dockerfile
  monicar-track-alert/build.gradle
  monicar-track-alert/src/main/java/org/trackalert/TrackAlertApplication.java
  monicar-track-alert/src/main/java/org/trackalert/application/TrackAlertService.java
  monicar-track-alert/src/main/java/org/trackalert/application/port/TrackAlertRepository.java
  monicar-track-alert/src/main/java/org/trackalert/domain/command/TrackAlertCreate.java
  monicar-track-alert/src/main/java/org/trackalert/presentation/TrackAlertController.java
  monicar-track-alert/src/main/java/org/trackalert/presentation/request/TrackAlertCreateRequest.java
  monicar-track-alert/src/main/java/org/trackalert/presentation/response/TrackAlertSimpleResponse.java
  monicar-track-alert/src/main/resources/application-dev.yml
  monicar-track-alert/src/main/resources/application.yml
Labels: 🔧 Chore

#364 fix: alarm 문제 수정
  monicar-control-center/src/main/java/org/controlcenter/alarm/application/AlarmService.java
  monicar-control-center/src/main/java/org/controlcenter/alarm/infrastructure/jpa/AlarmJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/common/scheduler/SseHeartbeatScheduler.java
Labels: 🐛 Fix

#368 refactor: 사용하지 않는 common 모듈 제거 및 readme 일부 내용 수정
  README.md
  monicar-collector/build.gradle
  monicar-collector/src/main/java/org/collector/CollectorApplication.java
  monicar-collector/src/main/java/org/collector/consumer/CycleInfoConsumer.java
  monicar-common/build.gradle
  monicar-common/src/main/java/org/common/TestBean.java
  monicar-common/src/main/java/org/common/dto/CListRequest.java
  monicar-common/src/main/java/org/common/dto/CommonResponse.java
  monicar-common/src/main/java/org/common/dto/CycleInfoRequest.java
  monicar-common/src/main/java/org/common/dto/GCD.java
  monicar-common/src/main/java/org/common/dto/ResponseCode.java
  monicar-common/src/main/resources/application.yml
  monicar-emulator/build.gradle
  monicar-emulator/src/main/java/org/emulator/device/application/port/VehicleEventSender.java
  monicar-event-hub/build.gradle
  settings.gradle
Labels: ♻️ Refactor

#370 chore: 시연 영상을 위한 세팅 수정
  monicar-control-center/src/main/resources/data/init-data.sql
  monicar-emulator/simulation/start-three-containers.sh
  monicar-emulator/src/main/java/org/emulator/EmulatorApplication.java
  monicar-emulator/src/main/resources/application.yml
  monicar-emulator/src/main/resources/templates/home.html
  monicar-event-hub/src/main/resources/application-dev.yml
Labels: 🔧 Chore

#374 docs: 자잘한 내용 수정
  README.md
Labels: 📝 Docs

#375 Update README.md
  README.md
  monicar-control-center/src/main/java/org/controlcenter/common/util/JWTTokenValidator.java
Labels: 🐛 Fix, 📝 Docs

#378 docs: 난아님 자료 반영
  README.md
Labels: 📝 Docs

#379 docs: Readme -> BE TroubleShooting 구체화
  README.md
Labels: 📝 Docs
