Repository Kernel360/KDEV3_monicar_BE, pull requests merged in 2025-01, with the labels that each got.

#26 feat: 관제 센터 전역 예외 처리 추가
  monicar-control-center/src/main/java/org/controlcenter/common/exception/BusinessException.java
  monicar-control-center/src/main/java/org/controlcenter/common/exception/GlobalExceptionHandler.java
Labels: ✨ Feat

#50 [feature] 테이블 ddl 생성
  .gitignore
  build.gradle
  docker/docker-compose.yml
  monicar-control-center/build.gradle
  monicar-control-center/src/main/resources/application-dev.yml
  monicar-control-center/src/main/resources/application.yml
  monicar-control-center/src/main/resources/data/init-data.sql
  monicar-control-center/src/main/resources/schema/init-schema.sql
Labels: ✨ Feat, 🔧 Chore

#48 [Refactor] 주기 정보 단건 저장시 코드 리팩토링
  monicar-collector/src/main/java/org/collector/common/annotation/MatchCycleSize.java
  monicar-collector/src/main/java/org/collector/common/validation/CycleCountValidator.java
  monicar-collector/src/main/java/org/collector/domain/CycleInfo.java
  monicar-collector/src/main/java/org/collector/presentation/dto/CListRequest.java
  monicar-collector/src/main/java/org/collector/presentation/dto/CycleInfoRequest.java
Labels: ♻️ Refactor

#49 [test] http 요청 테스트
  monicar-emulator/build.gradle
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/external/RestClientService.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/external/RestClientVehicleCommandSender.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/external/UrlPathEnum.java
  monicar-emulator/src/test/java/org/emulator/device/infrastructure/external/RestClientServiceTest.java
Labels: ✅ Test

#56 fix: 공통 응답 클래스 로직 수정 및 PR 템플릿 위치 수정
  .github/PULL_REQUEST_TEMPLATE.md
  monicar-control-center/src/main/java/org/controlcenter/common/exception/BusinessException.java
  monicar-control-center/src/main/java/org/controlcenter/common/exception/GlobalExceptionHandler.java
  monicar-control-center/src/main/java/org/controlcenter/common/response/BaseResponse.java
  monicar-control-center/src/main/java/org/controlcenter/common/response/code/ErrorCode.java
  monicar-control-center/src/main/java/org/controlcenter/common/response/code/SuccessCode.java
  monicar-control-center/src/main/java/org/controlcenter/dto/BaseResponse.java
  monicar-control-center/src/main/java/org/controlcenter/dto/ErrorCode.java
  monicar-control-center/src/main/java/org/controlcenter/dto/SuccessCode.java
Labels: 🐛 Fix

#60 [Feature] Collector 모듈 내 vehicle entity 생성
  monicar-collector/src/main/java/org/collector/application/CycleInfoService.java
  monicar-collector/src/main/java/org/collector/domain/CycleInfo.java
  monicar-collector/src/main/java/org/collector/domain/Vehicle.java
  monicar-collector/src/main/java/org/collector/presentation/dto/CListRequest.java
  monicar-collector/src/main/java/org/collector/presentation/dto/CycleInfoRequest.java
Labels: ✨ Feat, priority

#63 feat: 테이블 엔티티 설계
  monicar-control-center/build.gradle
  monicar-control-center/src/main/java/org/controlcenter/ControlCenterApplication.java
  monicar-control-center/src/main/java/org/controlcenter/alarm/domain/Alarm.java
  monicar-control-center/src/main/java/org/controlcenter/alarm/domain/AlarmStatus.java
  monicar-control-center/src/main/java/org/controlcenter/alarm/infrastructure/jpa/AlarmJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/alarm/infrastructure/jpa/entity/AlarmEntity.java
  monicar-control-center/src/main/java/org/controlcenter/common/exception/BusinessException.java
  monicar-control-center/src/main/java/org/controlcenter/company/domain/Company.java
  monicar-control-center/src/main/java/org/controlcenter/company/domain/Department.java
  monicar-control-center/src/main/java/org/controlcenter/company/domain/Manager.java
  monicar-control-center/src/main/java/org/controlcenter/company/domain/Role.java
  monicar-control-center/src/main/java/org/controlcenter/company/infrastructure/jpa/CompanyJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/company/infrastructure/jpa/DepartmentJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/company/infrastructure/jpa/ManagerJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/company/infrastructure/jpa/entity/CompanyEntity.java
  monicar-control-center/src/main/java/org/controlcenter/company/infrastructure/jpa/entity/DepartmentEntity.java
  monicar-control-center/src/main/java/org/controlcenter/company/infrastructure/jpa/entity/ManagerEntity.java
  monicar-control-center/src/main/java/org/controlcenter/config/JpaConfig.java
  monicar-control-center/src/main/java/org/controlcenter/geoinfo/domain/CycleInfo.java
  monicar-control-center/src/main/java/org/controlcenter/geoinfo/domain/GpsStatus.java
  monicar-control-center/src/main/java/org/controlcenter/geoinfo/infrastructure/jpa/CycleInfoJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/geoinfo/infrastructure/jpa/entity/CycleInfoEntity.java
  monicar-control-center/src/main/java/org/controlcenter/history/domain/DrivingHistory.java
  monicar-control-center/src/main/java/org/controlcenter/history/infrastructure/jpa/DrivingHistoryJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/history/infrastructure/jpa/entity/DrivingHistoryEntity.java
  monicar-control-center/src/main/java/org/controlcenter/notice/domain/Notice.java
  monicar-control-center/src/main/java/org/controlcenter/notice/infrastructure/jpa/NoticeJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/notice/infrastructure/jpa/entity/NoticeEntity.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/VehicleEvent.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/VehicleEventType.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/VehicleInformation.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/VehicleType.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/VehicleEventJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/VehicleInformationJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/VehicleTypesJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/entity/VehicleEventEntity.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/entity/VehicleInformationEntity.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/entity/VehicleTypeEntity.java
  monicar-control-center/src/main/resources/schema/init-schema.sql
  monicar-control-center/src/test/java/org/controlcenter/jpa/JpaTest.java
  monicar-control-center/src/test/resources/application-test.yml
Labels: ✨ Feat, 💄 Style, 🔧 Chore

#66 feat: 차량 추적 및 알람 관련 모듈 생성
  monicar-track-alert/build.gradle
  monicar-track-alert/src/main/java/org/trackalert/TrackAlertApplication.java
  monicar-track-alert/src/main/java/org/trackalert/application/TrackAlertService.java
  monicar-track-alert/src/main/java/org/trackalert/application/port/TrackAlertRepository.java
  monicar-track-alert/src/main/java/org/trackalert/domain/command/TrackAlertCreate.java
  monicar-track-alert/src/main/java/org/trackalert/presentation/TrackAlertController.java
  monicar-track-alert/src/main/java/org/trackalert/presentation/request/TrackAlertCreateRequest.java
  monicar-track-alert/src/main/java/org/trackalert/presentation/response/TrackAlertSimpleResponse.java
  monicar-track-alert/src/main/resources/application-dev.yml
  monicar-track-alert/src/main/resources/application.yml
  settings.gradle
Labels: ✨ Feat

#65 feat: 업체 생성 api 개발
  monicar-control-center/build.gradle
  monicar-control-center/src/main/java/org/controlcenter/common/response/code/ErrorCode.java
  monicar-control-center/src/main/java/org/controlcenter/company/application/CompanyService.java
  monicar-control-center/src/main/java/org/controlcenter/company/application/port/CompanyRepository.java
  monicar-control-center/src/main/java/org/controlcenter/company/domain/Company.java
  monicar-control-center/src/main/java/org/controlcenter/company/domain/CompanyCreate.java
  monicar-control-center/src/main/java/org/controlcenter/company/infrastructure/jpa/CompanyJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/company/infrastructure/jpa/CompanyRepositoryAdapter.java
  monicar-control-center/src/main/java/org/controlcenter/company/presentation/CompanyController.java
  monicar-control-center/src/main/java/org/controlcenter/company/presentation/dto/CompanyCreateRequest.java
  monicar-control-center/src/main/java/org/controlcenter/company/presentation/dto/SimpleCompanyResponse.java
  monicar-control-center/src/test/java/org/controlcenter/company/application/CompanyServiceTest.java
  monicar-control-center/src/test/java/org/controlcenter/company/domain/CompanyCreateTest.java
  monicar-control-center/src/test/java/org/controlcenter/company/domain/CompanyTest.java
  monicar-control-center/src/test/java/org/controlcenter/company/presentation/CompanyControllerTest.java
Labels: ✨ Feat, ✅ Test

#72 [fix] mdn 타입 변경
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/VehicleInformation.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/entity/VehicleInformationEntity.java
  monicar-control-center/src/main/resources/schema/init-schema.sql
Labels: 🐛 Fix, priority

#68 feat: 차량 정보 조회 API 구현
  monicar-control-center/build.gradle
  monicar-control-center/src/main/java/org/controlcenter/config/QuerydslConfig.java
  monicar-control-center/src/main/java/org/controlcenter/geoinfo/domain/CycleInfo.java
  monicar-control-center/src/main/java/org/controlcenter/geoinfo/infrastructure/jpa/entity/CycleInfoEntity.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/VehicleInformation.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/VehicleQueryRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/entity/VehicleInformationEntity.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/mybatis/MyBatisVehicleInfoMapper.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/VehicleController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/dto/VehicleInfoResponse.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/dto/VehicleInfoSearchRequest.java
  monicar-control-center/src/main/resources/schema/init-schema.sql
  monicar-control-center/src/test/java/org/controlcenter/jpa/JpaTest.java
Labels: ✨ Feat, ♻️ Refactor

#75 chore: 패키지 이름 수정
  monicar-control-center/src/main/java/org/controlcenter/cycleinfo/domain/CycleInfo.java
  monicar-control-center/src/main/java/org/controlcenter/cycleinfo/domain/GpsStatus.java
  monicar-control-center/src/main/java/org/controlcenter/cycleinfo/infrastructure/jpa/CycleInfoJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/cycleinfo/infrastructure/jpa/entity/CycleInfoEntity.java
  monicar-control-center/src/test/java/org/controlcenter/jpa/JpaTest.java
Labels: 🔧 Chore

#73 [Feature] collector모듈 내에 Producer, Consumer구현
  docker/docker-compose.yml
  monicar-collector/build.gradle
  monicar-collector/src/main/java/org/collector/application/CycleInfoService.java
  monicar-collector/src/main/java/org/collector/common/response/CommonResponse.java
  monicar-collector/src/main/java/org/collector/config/KafkaConfig.java
  monicar-collector/src/main/java/org/collector/consumer/CycleInfoConsumer.java
  monicar-collector/src/main/java/org/collector/domain/CycleInfo.java
  monicar-collector/src/main/java/org/collector/domain/VehicleInformation.java
  monicar-collector/src/main/java/org/collector/infrastructure/repository/VehicleInformationRepository.java
  monicar-collector/src/main/java/org/collector/presentation/CycleInfoController.java
  monicar-collector/src/main/java/org/collector/presentation/dto/CListRequest.java
  monicar-collector/src/main/java/org/collector/presentation/dto/CycleInfoRequest.java
  monicar-collector/src/main/java/org/collector/producer/CycleInfoProducer.java
  monicar-collector/src/main/resources/application.yml
Labels: ✨ Feat

#77 [refactor] 위, 경도값 올바르게 예외처리하도록 수정
  monicar-collector/src/main/java/org/collector/domain/CycleInfo.java
  monicar-collector/src/main/java/org/collector/presentation/dto/CListRequest.java
Labels: 🐛 Fix, priority

#79 [Feature] 주기정보 저장시, 유효성검사에 실패할 경우 올바르게 mdn을 반환하도록 변경
  monicar-collector/src/main/java/org/collector/application/CycleInfoService.java
  monicar-collector/src/main/java/org/collector/common/exception/CustomException.java
  monicar-collector/src/main/java/org/collector/common/exception/GlobalExceptionHandler.java
  monicar-collector/src/main/java/org/collector/common/response/ResponseCode.java
  monicar-collector/src/main/java/org/collector/domain/CycleInfo.java
  monicar-collector/src/main/java/org/collector/domain/VehicleInformation.java
  monicar-collector/src/main/java/org/collector/infrastructure/repository/VehicleInformationRepository.java
  monicar-collector/src/main/java/org/collector/presentation/dto/CListRequest.java
  monicar-collector/src/main/java/org/collector/presentation/dto/CycleInfoRequest.java
Labels: 🐛 Fix

#81 feat: 커스텀 페이지네이션 추가
  monicar-control-center/src/main/java/org/controlcenter/common/response/PageResponse.java
Labels: ✨ Feat

#91 feature: 운행일지 기본 조회(전체 차량 단순 조회) 기능 구현
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/DrivingLogService.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/port/DrivingLogRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/DrivingLog.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/VehicleInformation.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/VehicleStatus.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/DrivingLogJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/entity/VehicleInformationEntity.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/DrivingLogController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/dto/DrivingLogResponse.java
  monicar-control-center/src/main/resources/application-dev.yml
  monicar-control-center/src/main/resources/data/init-data.sql
  monicar-control-center/src/main/resources/schema/init-schema.sql
  monicar-control-center/src/test/java/org/controlcenter/jpa/JpaTest.java
Labels: ✨ Feat

#93 [chore] ci.yml 테스트
  .github/workflows/ci.yml
  monicar-collector/Dockerfile
  monicar-control-center/Dockerfile
  monicar-track-alert/Dockerfile
Labels: 🔧 Chore

#92 feat: 차량 경로 조회 기능 구현
  .gitignore
  docker/docker-compose.yml
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/VehicleService.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/port/VehicleRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/VehicleQueryRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/VehicleInformationRepositoryAdapter.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/mybatis/MyBatisVehicleInfoMapper.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/VehicleController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/dto/RouteResponse.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/dto/VehicleInfoSearchRequest.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/dto/VehicleRouteResponse.java
Labels: ✨ Feat

#100 fix: 카프카 프로듀서 컨수머 직렬화 역직렬화 문제
  docker/docker-compose.yml
  monicar-collector/src/main/java/org/collector/application/CycleInfoService.java
  monicar-collector/src/main/java/org/collector/config/JpaConfig.java
  monicar-collector/src/main/java/org/collector/config/KafkaConfig.java
  monicar-collector/src/main/java/org/collector/consumer/CycleInfoConsumer.java
  monicar-collector/src/main/java/org/collector/domain/CycleInfo.java
  monicar-collector/src/main/java/org/collector/domain/VehicleInformation.java
  monicar-collector/src/main/java/org/collector/domain/VehicleStatus.java
  monicar-collector/src/main/java/org/collector/domain/VehicleType.java
  monicar-collector/src/main/java/org/collector/infrastructure/repository/VehicleInformationRepository.java
  monicar-collector/src/main/java/org/collector/presentation/CycleInfoController.java
  monicar-collector/src/main/java/org/collector/presentation/dto/CListRequest.java
  monicar-collector/src/main/java/org/collector/presentation/dto/GCD.java
  monicar-collector/src/main/java/org/collector/producer/CycleInfoProducer.java
  monicar-collector/src/main/resources/application.yml
  monicar-control-center/src/main/resources/data/init-data.sql
  monicar-emulator/src/main/java/org/emulator/config/KafkaConfig.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/external/command/CycleInfoCommand.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/messaging/KafkaCycleInfoEventPublisher.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/messaging/TypeIdInterceptor.java
  monicar-emulator/src/main/resources/application.yml
Labels: 🐛 Fix, ♻️ Refactor

#115 chore: 경도 표기법을 기존 lon에서 lng로 수정
  monicar-collector/src/main/java/org/collector/domain/CycleInfo.java
  monicar-collector/src/main/java/org/collector/presentation/dto/CListRequest.java
  monicar-common/src/main/java/org/common/dto/CListRequest.java
  monicar-control-center/src/main/java/org/controlcenter/cycleinfo/domain/CycleInfo.java
  monicar-control-center/src/main/java/org/controlcenter/cycleinfo/infrastructure/jpa/entity/CycleInfoEntity.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/mybatis/MyBatisVehicleInfoMapper.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/dto/RouteResponse.java
  monicar-control-center/src/main/resources/schema/init-schema.sql
  monicar-control-center/src/test/java/org/controlcenter/jpa/JpaTest.java
  monicar-emulator/src/main/java/org/emulator/device/application/VehicleService.java
  monicar-emulator/src/main/java/org/emulator/device/domain/CycleInfo.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/external/command/GeoList.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/external/command/OffCommand.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/external/command/OnCommand.java
  monicar-emulator/src/main/java/org/emulator/pipe/Gps.java
Labels: 🔧 Chore

#116 feat: 공지사항 api 구현
  monicar-control-center/src/main/java/org/controlcenter/notice/application/NoticeRepository.java
  monicar-control-center/src/main/java/org/controlcenter/notice/infrastructure/jpa/NoticeRepositoryAdapter.java
  monicar-control-center/src/main/java/org/controlcenter/notice/presentation/NoticeController.java
  monicar-control-center/src/main/java/org/controlcenter/notice/presentation/SimpleNoticeResponse.java
  monicar-control-center/src/main/resources/data/init-data.sql
  monicar-control-center/src/test/java/org/controlcenter/notice/presentation/NoticeControllerTest.java
Labels: ✨ Feat, ✅ Test

#112 Feature/#87 response api for vehicle on request
  .gitignore
  monicar-control-center/src/main/java/org/controlcenter/common/response/code/ResponseCode.java
  monicar-control-center/src/main/java/org/controlcenter/company/domain/Company.java
  monicar-control-center/src/main/java/org/controlcenter/cycleinfo/domain/GpsStatus.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/VehicleService.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/port/VehicleEventRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/port/VehicleRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/VehicleEvent.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/VehicleEventCreate.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/http/request.http
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/VehicleEventRepositoryAdapter.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/VehicleInformationJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/VehicleInformationRepositoryAdapter.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/VehicleController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/dto/CommonResponse.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/dto/KeyOnRequest.java
Labels: ✨ Feat

#113 [chore] multi-module-cicd
  .github/workflows/cicd.yml
  monicar-collector/src/main/java/org/collector/CollectorApplication.java
  monicar-collector/src/main/resources/application-dev.yml
  monicar-collector/src/main/resources/application.yml
  monicar-control-center/src/main/java/org/controlcenter/ControlCenterApplication.java
Labels: 🔧 Chore

#118 feat: 운행일지 상세 조회 기능 API 구현 및 차량정보 엔티티 필드 추가
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/DrivingLogService.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/port/DrivingLogRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/BusinessInfo.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/BusinessMileageDetails.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/DrivingInfo.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/DrivingLogDetailsContent.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/SpecificVehicleInformation.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/VehicleHeaderInfo.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/VehicleInformation.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/DrivingLogJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/entity/VehicleInformationEntity.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/DrivingLogController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/dto/DrivingUserInfo.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/dto/VehicleDrivingLogDetailsResponse.java
  monicar-control-center/src/main/resources/data/init-data.sql
  monicar-control-center/src/main/resources/schema/init-schema.sql
Labels: ✨ Feat

#117 feat: 에뮬레이터 전역 예외 처리
  monicar-control-center/src/test/java/org/controlcenter/jpa/JpaTest.java
  monicar-emulator/src/main/java/org/emulator/device/VehicleConstant.java
  monicar-emulator/src/main/java/org/emulator/device/application/VehicleService.java
  monicar-emulator/src/main/java/org/emulator/device/application/port/VehicleCommandSender.java
  monicar-emulator/src/main/java/org/emulator/device/common/exception/BusinessException.java
  monicar-emulator/src/main/java/org/emulator/device/common/exception/GlobalExceptionHandler.java
  monicar-emulator/src/main/java/org/emulator/device/common/response/BaseResponse.java
  monicar-emulator/src/main/java/org/emulator/device/common/response/ErrorCode.java
  monicar-emulator/src/main/java/org/emulator/device/common/response/SuccessCode.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/external/RestClientService.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/external/RestClientVehicleCommandSender.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/util/DirectionCalculator.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/util/DistanceCalculator.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/util/HeaderUtils.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/util/RequestUtils.java
  monicar-emulator/src/main/java/org/emulator/device/presentation/VehicleController.java
  monicar-emulator/src/test/java/org/emulator/device/infrastructure/external/RestClientServiceTest.java
  monicar-emulator/src/test/java/org/emulator/device/presentation/VehicleControllerTest.java
Labels: 🐛 Fix, ✅ Test

#122 feat: Swagger api 문서화 추가
  monicar-control-center/build.gradle
  monicar-control-center/src/main/java/org/controlcenter/config/SwaggerConfig.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/DrivingLogService.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/DrivingLogController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/swagger/DrivingLogApi.java
  monicar-control-center/src/main/resources/data/init-data.sql
  monicar-control-center/src/main/resources/schema/init-schema.sql
Labels: ✨ Feat

#123 [Feature] 애뮬레이터 내 프로듀서 코드 분리
  monicar-producer/build.gradle
  monicar-producer/src/main/java/org/producer/ProducerApplication.java
  monicar-producer/src/main/java/org/producer/common/constant/VehicleConstant.java
  monicar-producer/src/main/java/org/producer/common/exception/BusinessException.java
  monicar-producer/src/main/java/org/producer/common/response/ErrorCode.java
  monicar-producer/src/main/java/org/producer/config/KafkaConfig.java
  monicar-producer/src/main/java/org/producer/dto/CycleInfoCommand.java
  monicar-producer/src/main/java/org/producer/dto/CycleInfoListCommand.java
  monicar-producer/src/main/java/org/producer/dto/FixedVehicleInfo.java
  monicar-producer/src/main/java/org/producer/dto/GpsStatus.java
  monicar-producer/src/main/java/org/producer/producer/CycleInfoEventPublisher.java
  monicar-producer/src/main/java/org/producer/producer/KafkaCycleInfoEventPublisher.java
  monicar-producer/src/main/java/org/producer/producer/TypeIdInterceptor.java
  monicar-producer/src/main/resources/application.yml
  settings.gradle
Labels: ✨ Feat

#128 chore: ddl jpa 엔티티 수정
  monicar-control-center/src/main/java/org/controlcenter/cycleinfo/domain/CycleInfo.java
  monicar-control-center/src/main/java/org/controlcenter/cycleinfo/infrastructure/jpa/entity/CycleInfoEntity.java
  monicar-control-center/src/main/java/org/controlcenter/history/domain/DrivingHistory.java
  monicar-control-center/src/main/java/org/controlcenter/history/domain/UsePurpose.java
  monicar-control-center/src/main/java/org/controlcenter/history/infrastructure/jpa/entity/DrivingHistoryEntity.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/VehicleEvent.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/VehicleInformation.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/DrivingLogJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/entity/VehicleEventEntity.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/entity/VehicleInformationEntity.java
  monicar-control-center/src/main/resources/data/init-data.sql
  monicar-control-center/src/main/resources/schema/init-schema.sql
  monicar-control-center/src/test/java/org/controlcenter/jpa/JpaTest.java
Labels: 🔧 Chore, priority

#125 feat: 차량상세정보모달 조회api구현
  monicar-control-center/src/main/java/org/controlcenter/history/domain/DrivingHistory.java
  monicar-control-center/src/main/java/org/controlcenter/history/infrastructure/jpa/entity/DrivingHistoryEntity.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/VehicleQueryRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/mybatis/MyBatisVehicleInfoMapper.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/VehicleController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/dto/VehicleModalResponse.java
Labels: ✨ Feat, 🔧 Chore

#126 feat: on 요청시 운행내역 데이터 생성
  monicar-collector/src/main/java/org/collector/application/CycleInfoService.java
  monicar-control-center/src/main/java/org/controlcenter/common/response/BaseResponse.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/VehicleEventService.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/port/VehicleEventRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/VehicleEvent.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/VehicleEventType.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/VehicleEventJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/VehicleEventRepositoryAdapter.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/VehicleController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/dto/KeyOnRequest.java
  monicar-control-center/src/test/java/org/controlcenter/vehicle/application/VehicleEventServiceTest.java
  monicar-control-center/src/test/java/org/controlcenter/vehicle/presentation/VehicleControllerTest.java
  monicar-emulator/src/main/java/org/emulator/device/application/VehicleService.java
  monicar-emulator/src/main/java/org/emulator/device/application/port/EmulatorRepository.java
  monicar-emulator/src/main/java/org/emulator/device/domain/VehicleInfo.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/GpsTracker.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/entity/VehicleEntity.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/repository/InMemoryEmulatorRepository.java
  monicar-emulator/src/main/java/org/emulator/device/presentation/VehicleController.java
  monicar-emulator/src/test/java/org/emulator/device/presentation/VehicleControllerTest.java
Labels: 🐛 Fix, ✨ Feat

#134 chore: 모듈 이름 변경에 따른 패키지 이름 수정 및 파일 수정
  monicar-event-hub/build.gradle
  monicar-event-hub/src/main/java/org/eventhub/EventHubApplication.java
  monicar-event-hub/src/main/java/org/eventhub/common/constant/VehicleConstant.java
  monicar-event-hub/src/main/java/org/eventhub/common/exception/BusinessException.java
  monicar-event-hub/src/main/java/org/eventhub/common/response/ErrorCode.java
  monicar-event-hub/src/main/java/org/eventhub/config/KafkaConfig.java
  monicar-event-hub/src/main/java/org/eventhub/dto/CycleInfoCommand.java
  monicar-event-hub/src/main/java/org/eventhub/dto/CycleInfoListCommand.java
  monicar-event-hub/src/main/java/org/eventhub/dto/FixedVehicleInfo.java
  monicar-event-hub/src/main/java/org/eventhub/dto/GpsStatus.java
  monicar-event-hub/src/main/java/org/eventhub/producer/CycleInfoEventPublisher.java
  monicar-event-hub/src/main/java/org/eventhub/producer/KafkaCycleInfoEventPublisher.java
  monicar-event-hub/src/main/java/org/eventhub/producer/TypeIdInterceptor.java
  monicar-event-hub/src/main/resources/application.yml
  settings.gradle
Labels: 🔧 Chore

#139 feat: 지도 클러스터링 조회 기능 구현
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/VehicleClusteringService.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/port/VehicleRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/cluster/ClusterCreateCommand.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/cluster/CoordinateDivider.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/cluster/GeoClustering.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/cluster/GeoCoordinate.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/VehicleInformationRepositoryAdapter.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/VehicleQueryRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/VehicleInformationRepositoryAdapter.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/mybatis/MyBatisVehicleInfoMapper.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/mybatis/dto/GeoCoordinateDto.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/VehicleController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/dto/GeoClusteringResponse.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/dto/RouteResponse.java
  monicar-control-center/src/main/resources/data/init-data.sql
  monicar-control-center/src/main/resources/schema/init-schema.sql
  monicar-control-center/src/test/java/org/controlcenter/vehicle/domain/cluster/CoordinateDividerTest.java
Labels: 🐛 Fix, ✨ Feat

#146 feat: 시동 여부에 따른 전체 차량 수 조회
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/VehicleQueryRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/mybatis/MyBatisVehicleInfoMapper.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/VehicleController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/dto/VehicleEngineStatusResponse.java
  monicar-control-center/src/main/resources/data/init-data.sql
Labels: ✨ Feat

#149 feat: 애뮬레이터 화면 구현
  monicar-emulator/build.gradle
  monicar-emulator/src/main/java/org/emulator/device/presentation/VehicleApiController.java
  monicar-emulator/src/main/java/org/emulator/device/presentation/VehicleController.java
  monicar-emulator/src/main/resources/templates/home.html
Labels: ✨ Feat

#151 chore: swagger 설정 추가
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/VehicleController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/swagger/VehicleApi.java
  monicar-emulator/src/main/resources/style/home.css
Labels: 💄 Style, 🔧 Chore

#155 refactor: 개별 차량 상세 정보 조회 모달에 누락된 정보 추가
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/VehicleQueryRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/mybatis/MyBatisVehicleInfoMapper.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/VehicleController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/dto/VehicleModalResponse.java
Labels: ♻️ Refactor

#147 feat: emulator의 gps 데이터 전송 방법 변경
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/VehicleController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/swagger/VehicleApi.java
  monicar-control-center/src/test/java/org/controlcenter/vehicle/application/VehicleEventServiceTest.java
  monicar-emulator/src/main/java/org/emulator/config/KafkaConfig.java
  monicar-emulator/src/main/java/org/emulator/device/application/VehicleService.java
  monicar-emulator/src/main/java/org/emulator/device/application/port/CycleInfoEventPublisher.java
  monicar-emulator/src/main/java/org/emulator/device/application/port/VehicleEventHttpClient.java
  monicar-emulator/src/main/java/org/emulator/device/common/response/ErrorCode.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/GpsTracker.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/external/RestClientService.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/external/RestClientVehicleCommandSender.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/external/VehicleEventRestClient.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/messaging/KafkaCycleInfoEventPublisher.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/messaging/TypeIdInterceptor.java
  monicar-emulator/src/main/resources/application.yml
  monicar-emulator/src/test/java/org/emulator/device/infrastructure/external/RestClientServiceTest.java
  monicar-emulator/src/test/java/org/emulator/device/presentation/VehicleApiControllerTest.java
  monicar-emulator/test.http
  monicar-event-hub/src/main/java/org/eventhub/application/port/CycleInfoEventPublisher.java
  monicar-event-hub/src/main/java/org/eventhub/common/response/BaseResponse.java
  monicar-event-hub/src/main/java/org/eventhub/domain/CycleInfo.java
  monicar-event-hub/src/main/java/org/eventhub/domain/CycleInfoList.java
  monicar-event-hub/src/main/java/org/eventhub/infrastructure/messaging/CycleInfoEventPublisher.java
  monicar-event-hub/src/main/java/org/eventhub/infrastructure/messaging/KafkaCycleInfoEventPublisher.java
  monicar-event-hub/src/main/java/org/eventhub/infrastructure/messaging/command/CycleInfoCommand.java
  monicar-event-hub/src/main/java/org/eventhub/infrastructure/messaging/command/CycleInfoListCommand.java
  monicar-event-hub/src/main/java/org/eventhub/presentation/CycleInfoController.java
  monicar-event-hub/src/main/java/org/eventhub/presentation/CycleInfoListRequest.java
  monicar-event-hub/src/main/java/org/eventhub/presentation/SimpleCycleInfoRequest.java
  monicar-event-hub/src/main/resources/application.yml
Labels: ✨ Feat, ♻️ Refactor

#148 feat: event hub에서 gps 데이터 kafka send
  monicar-collector/src/main/java/org/collector/config/CycleInfoRequestDeserializer.java
  monicar-collector/src/main/java/org/collector/config/KafkaConfig.java
  monicar-collector/src/main/java/org/collector/domain/CycleInfo.java
  monicar-collector/src/main/java/org/collector/presentation/dto/CListRequest.java
  monicar-emulator/src/test/java/org/emulator/config/ApiConfigTest.java
  monicar-event-hub/src/main/java/org/eventhub/config/KafkaProducerConfig.java
  monicar-event-hub/src/main/java/org/eventhub/presentation/CycleInfoController.java
Labels: ✨ Feat, ♻️ Refactor

#159 feat: 지도 클러스터링 조회시 특정 카운트값에 따라 개별 차량 정보 반환 조회 구현
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/VehicleClusteringService.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/port/VehicleRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/cluster/GeoCoordinateDetails.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/VehicleInformationRepositoryAdapter.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/mybatis/MyBatisVehicleInfoMapper.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/mybatis/dto/GeoCoordinateDetailsDto.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/VehicleController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/dto/GeoCoordinateDetailsResponse.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/swagger/VehicleApi.java
Labels: ✨ Feat

#156 [Chore] event hub 모듈 배포
  .github/workflows/cicd.yml
  monicar-collector/src/main/resources/application.yml
  monicar-control-center/src/main/resources/application.yml
  monicar-event-hub/Dockerfile
  monicar-event-hub/src/main/resources/application-dev.yml
  monicar-event-hub/src/main/resources/application.yml
Labels: 🔧 Chore, priority

#158 feat: 응답 데이터 변경으로 인한 운행일지 상세 조회 쿼리 수정
  monicar-control-center/src/main/java/org/controlcenter/common/response/code/ErrorCode.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/DrivingLogService.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/port/DrivingLogRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/BusinessDrivingDetails.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/BusinessInfo.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/BusinessMileageDetails.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/DrivingInfo.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/DrivingLogDetailsContent.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/DrivingLogSummary.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/DrivingUserInfo.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/VehicleFooterInfo.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/DrivingLogJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/VehicleController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/dto/VehicleDrivingLogDetailsResponse.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/swagger/VehicleApi.java
  monicar-control-center/src/main/resources/application-dev.yml
  monicar-control-center/src/main/resources/data/init-data.sql
Labels: 🐛 Fix

#163 fix: 운행일지 기본 조회 API 응답 수정
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/DrivingLog.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/DrivingLogJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/dto/DrivingLogResponse.java
  monicar-control-center/src/main/resources/data/init-data.sql
Labels: 🐛 Fix

#167 feat: 스프링 시큐리티 기본 셋팅 적용
  .gitignore
  monicar-control-center/build.gradle
  monicar-control-center/src/main/java/org/controlcenter/config/CorsProperties.java
  monicar-control-center/src/main/java/org/controlcenter/config/SecurityConfig.java
  monicar-control-center/src/main/resources/application-dev.yml
Labels: ✨ Feat, priority

#164 feat: event hub datasource 설정
  monicar-emulator/src/main/java/org/emulator/device/VehicleConstant.java
  monicar-emulator/src/main/java/org/emulator/device/application/VehicleService.java
  monicar-emulator/src/main/java/org/emulator/device/application/port/VehicleEventSender.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/GpsTracker.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/external/VehicleEventRestClient.java
  monicar-event-hub/src/main/resources/application-dev.yml
Labels: ✨ Feat, ♻️ Refactor

#172 chore: 전송 주기 yml에서 설정하기
  monicar-control-center/src/test/java/org/controlcenter/company/presentation/CompanyControllerTest.java
  monicar-control-center/src/test/java/org/controlcenter/notice/presentation/NoticeControllerTest.java
  monicar-emulator/src/main/java/org/emulator/config/ApiConfig.java
  monicar-emulator/src/main/java/org/emulator/device/VehicleConstant.java
  monicar-emulator/src/main/java/org/emulator/device/domain/EmulatorTransmissionTimeProvider.java
  monicar-emulator/src/main/resources/application.yml
Labels: ♻️ Refactor

#171 [chore] cicd 파이프라인 일부 수정
  .github/workflows/cicd.yml
Labels: 🔧 Chore, priority

#177 feat: event-hub 모듈 health-check-api 추가
  monicar-event-hub/build.gradle
  monicar-event-hub/src/main/java/org/eventhub/config/SecurityConfig.java
  monicar-event-hub/src/main/java/org/eventhub/presentation/HealthCheckController.java
Labels: ✨ Feat, priority

#179 chore: cicd 수정
  .github/workflows/cicd.yml
Labels: 🔧 Chore

#187 fix: CI 환경변수 파일 추가
  .github/workflows/cicd.yml
Labels: 🐛 Fix

#189 fix: cicd 자동배포 구문 오류 문제 수정
  .github/workflows/cicd.yml
Labels: 🐛 Fix

#180 feature: 사용자 관련 API 추가
  .github/workflows/cicd.yml
  monicar-control-center/build.gradle
  monicar-control-center/src/main/java/org/controlcenter/common/exception/GlobalExceptionHandler.java
  monicar-control-center/src/main/java/org/controlcenter/common/exception/TokenValidationException.java
  monicar-control-center/src/main/java/org/controlcenter/common/response/code/ErrorCode.java
  monicar-control-center/src/main/java/org/controlcenter/common/security/CustomAuthenticationErrorHandler.java
  monicar-control-center/src/main/java/org/controlcenter/common/security/CustomAuthenticationFailureHandler.java
  monicar-control-center/src/main/java/org/controlcenter/common/security/CustomAuthenticationSuccessHandler.java
  monicar-control-center/src/main/java/org/controlcenter/common/security/CustomUserDetailService.java
  monicar-control-center/src/main/java/org/controlcenter/common/security/CustomUserDetails.java
  monicar-control-center/src/main/java/org/controlcenter/common/security/JWTFilter.java
  monicar-control-center/src/main/java/org/controlcenter/common/security/LoginFilter.java
  monicar-control-center/src/main/java/org/controlcenter/common/security/LoginRequest.java
  monicar-control-center/src/main/java/org/controlcenter/common/util/CookieUtil.java
  monicar-control-center/src/main/java/org/controlcenter/common/util/JWTTokenValidator.java
  monicar-control-center/src/main/java/org/controlcenter/common/util/JWTUtil.java
  monicar-control-center/src/main/java/org/controlcenter/common/util/RedisUtil.java
  monicar-control-center/src/main/java/org/controlcenter/company/application/AuthService.java
  monicar-control-center/src/main/java/org/controlcenter/company/domain/Manager.java
  monicar-control-center/src/main/java/org/controlcenter/company/domain/Role.java
  monicar-control-center/src/main/java/org/controlcenter/company/infrastructure/jpa/ManagerJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/company/infrastructure/jpa/entity/ManagerEntity.java
  monicar-control-center/src/main/java/org/controlcenter/company/presentation/AuthController.java
  monicar-control-center/src/main/java/org/controlcenter/company/presentation/ManagerController.java
  monicar-control-center/src/main/java/org/controlcenter/company/presentation/dto/LoginRequest.java
  monicar-control-center/src/main/java/org/controlcenter/company/presentation/swagger/ManagerApi.java
  monicar-control-center/src/main/java/org/controlcenter/config/PropertyConfig.java
  monicar-control-center/src/main/java/org/controlcenter/config/RedisConfig.java
  monicar-control-center/src/main/java/org/controlcenter/config/SecurityConfig.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/swagger/VehicleApi.java
  monicar-control-center/src/main/resources/application-dev.yml
  monicar-control-center/src/main/resources/data/init-data.sql
  monicar-control-center/src/main/resources/schema/init-schema.sql
  monicar-control-center/src/test/java/org/controlcenter/jpa/JpaTest.java
Labels: ✨ Feat

#173 fix(emulator): on 요청시 현재 위치 가져오기 로직 수정
  monicar-emulator/src/main/java/org/emulator/EmulatorApplication.java
  monicar-emulator/src/main/java/org/emulator/device/application/VehicleService.java
  monicar-emulator/src/main/java/org/emulator/device/application/port/EmulatorRepository.java
  monicar-emulator/src/main/java/org/emulator/device/application/port/LocationReceiver.java
  monicar-emulator/src/main/java/org/emulator/device/application/port/TransmissionTimeProvider.java
  monicar-emulator/src/main/java/org/emulator/device/application/port/VehicleEventSender.java
  monicar-emulator/src/main/java/org/emulator/device/common/response/ErrorCode.java
  monicar-emulator/src/main/java/org/emulator/device/domain/CycleInfo.java
  monicar-emulator/src/main/java/org/emulator/device/domain/EmulatorTransmissionTimeProvider.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/GpsPipeQueueReceiver.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/SensorTracker.java
  monicar-emulator/src/main/java/org/emulator/pipe/GpsPipeQueue.java
  monicar-emulator/src/main/java/org/emulator/sensor/GpsDetector.java
  monicar-emulator/src/main/java/org/emulator/sensor/GpsPipeQueueReceiver.java
  monicar-emulator/src/main/java/org/emulator/sensor/GpsSensor.java
  monicar-emulator/src/main/java/org/emulator/sensor/GpsTracker.java
  monicar-emulator/src/main/java/org/emulator/sensor/LocationHolder.java
  monicar-emulator/src/main/java/org/emulator/sensor/SensorDetector.java
  monicar-emulator/src/main/java/org/emulator/sensor/SensorTracker.java
  monicar-emulator/src/main/java/org/emulator/sensor/dto/Gps.java
  monicar-emulator/src/main/java/org/emulator/sensor/dto/GpsTime.java
  monicar-emulator/src/main/java/org/emulator/sensor/util/CycleTimeProvider.java
  monicar-emulator/src/main/java/org/emulator/sensor/util/DirectionCalculator.java
  monicar-emulator/src/main/java/org/emulator/sensor/util/DistanceCalculator.java
  monicar-emulator/src/main/java/org/emulator/sensor/util/MovementCalculator.java
  monicar-emulator/src/main/java/org/emulator/sensor/util/SpeedCalculator.java
  monicar-emulator/src/test/java/org/emulator/device/infrastructure/util/MovementCalculatorTest.java
Labels: 🐛 Fix

#175 fix: emulator와 event hub의 응답 로직 수정
  monicar-control-center/src/main/resources/data/init-data.sql
  monicar-emulator/src/main/java/org/emulator/device/application/VehicleService.java
  monicar-emulator/src/main/java/org/emulator/device/application/port/VehicleEventSender.java
  monicar-emulator/src/main/java/org/emulator/device/common/exception/GlobalExceptionHandler.java
  monicar-emulator/src/main/java/org/emulator/device/common/response/BaseResponse.java
  monicar-emulator/src/main/java/org/emulator/device/common/response/ErrorCode.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/external/RestClientService.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/external/VehicleEventRestClient.java
  monicar-emulator/src/main/java/org/emulator/device/infrastructure/external/command/OnCommand.java
  monicar-emulator/src/main/java/org/emulator/device/presentation/VehicleApiController.java
  monicar-emulator/src/main/java/org/emulator/sensor/GpsTracker.java
  monicar-emulator/src/test/java/org/emulator/device/infrastructure/external/RestClientServiceTest.java
  monicar-emulator/src/test/java/org/emulator/device/presentation/VehicleApiControllerTest.java
  monicar-emulator/src/test/key_on_request.http
  monicar-event-hub/src/main/java/org/eventhub/application/VehicleEventService.java
  monicar-event-hub/src/main/java/org/eventhub/common/FixedVehicleInfo.java
  monicar-event-hub/src/main/java/org/eventhub/common/constant/GlobalExceptionHandler.java
  monicar-event-hub/src/main/java/org/eventhub/common/constant/VehicleConstant.java
  monicar-event-hub/src/main/java/org/eventhub/common/exception/GlobalExceptionHandler.java
  monicar-event-hub/src/main/java/org/eventhub/common/response/BaseResponse.java
  monicar-event-hub/src/main/java/org/eventhub/common/response/EmulatorResponseCode.java
  monicar-event-hub/src/main/java/org/eventhub/common/response/ErrorCode.java
  monicar-event-hub/src/main/java/org/eventhub/infrastructure/repository/jpa/VehicleEventJpaRepository.java
  monicar-event-hub/src/main/java/org/eventhub/presentation/CycleInfoController.java
  monicar-event-hub/src/main/java/org/eventhub/presentation/KeyOnRequest.java
  monicar-event-hub/src/main/java/org/eventhub/presentation/OnOffController.java
  monicar-event-hub/src/test/java/org/eventhub/presentation/OnOffControllerTest.java
Labels: 🐛 Fix, ♻️ Refactor

#190 chore: 모니터링 시스템
  .gitignore
  monicar-control-center/src/main/java/org/controlcenter/company/presentation/ManagerController.java
  monicar-control-center/src/test/resources/application-test.yml
  monicar-emulator/src/main/resources/logback-spring.xml
  monicar-event-hub/build.gradle
  monicar-event-hub/src/main/java/org/eventhub/config/SecurityConfig.java
  monicar-event-hub/src/main/resources/application-dev.yml
  monicar-event-hub/src/main/resources/application.yml
  monicar-event-hub/src/main/resources/logback-spring.xml
Labels: 🔧 Chore

#192 feat: 차량 등록 API 구현
  monicar-control-center/src/main/java/org/controlcenter/common/response/code/ErrorCode.java
  monicar-control-center/src/main/java/org/controlcenter/common/security/CustomUserDetailService.java
  monicar-control-center/src/main/java/org/controlcenter/common/security/JWTFilter.java
  monicar-control-center/src/main/java/org/controlcenter/common/util/CookieUtil.java
  monicar-control-center/src/main/java/org/controlcenter/common/util/JWTTokenValidator.java
  monicar-control-center/src/main/java/org/controlcenter/common/util/JWTUtil.java
  monicar-control-center/src/main/java/org/controlcenter/company/application/CompanyService.java
  monicar-control-center/src/main/java/org/controlcenter/company/presentation/AuthController.java
  monicar-control-center/src/main/java/org/controlcenter/company/presentation/ManagerController.java
  monicar-control-center/src/main/java/org/controlcenter/company/presentation/swagger/ManagerApi.java
  monicar-control-center/src/main/java/org/controlcenter/config/SecurityConfig.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/DrivingLogService.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/VehicleService.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/port/DrivingLogRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/port/VehicleRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/VehicleInformation.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/VehicleRegister.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/VehicleSortType.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/VehicleInformationRepositoryAdapter.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/DrivingLogJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/DrivingLogController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/VehicleController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/dto/VehicleRegisterRequest.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/swagger/DrivingLogApi.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/swagger/VehicleApi.java
  monicar-control-center/src/main/resources/application.yml
Labels: 🐛 Fix, ✨ Feat

#195 feat: 차량 등록 페이지 진입 시 차량종류 요청 API
  monicar-control-center/src/main/java/org/controlcenter/company/presentation/swagger/ManagerApi.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/port/VehicleTypeRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/VehicleTypeRepositoryAdapter.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/DrivingLogController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/dto/VehicleTypeResponse.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/swagger/DrivingLogApi.java
Labels: ✨ Feat

#196 feat: 차량 정보 삭제 API
  monicar-control-center/src/main/java/org/controlcenter/history/infrastructure/jpa/DrivingHistoryJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/history/infrastructure/jpa/entity/DrivingHistoryEntity.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/DrivingLogService.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/VehicleService.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/port/DrivingLogRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/DrivingLogJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/VehicleInformationJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/entity/VehicleInformationEntity.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/VehicleController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/swagger/VehicleApi.java
Labels: ✨ Feat

#217 fix: 프로덕션 환경 수정 및 차량 기본 조회 시 차량 상태값 변환 수정
  monicar-control-center/src/main/java/org/controlcenter/config/PropertyConfig.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/dto/DrivingLogResponse.java
Labels: 🐛 Fix

#219 fix: 액세스토큰 리프레시토큰 로직 수정
  monicar-control-center/src/main/java/org/controlcenter/common/util/JWTTokenValidator.java
  monicar-control-center/src/main/java/org/controlcenter/common/util/JWTUtil.java
Labels: 🐛 Fix

#228 fix: 대한민국 위도 경도 범위 수정
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/cluster/GeoCoordinate.java
Labels: ♻️ Refactor

#230 feature: 일별 운행기록 API 구현
  monicar-control-center/src/main/java/org/controlcenter/common/util/CookieUtil.java
  monicar-control-center/src/main/java/org/controlcenter/company/presentation/AuthController.java
  monicar-control-center/src/main/java/org/controlcenter/company/presentation/CompanyController.java
  monicar-control-center/src/main/java/org/controlcenter/company/presentation/swagger/AuthApi.java
  monicar-control-center/src/main/java/org/controlcenter/notice/presentation/NoticeController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/DrivingLogService.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/application/port/DrivingLogRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/DailyDrivingSummary.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/domain/Period.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/infrastructure/jpa/DrivingLogJpaRepository.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/DrivingLogController.java
  monicar-control-center/src/main/java/org/controlcenter/vehicle/presentation/VehicleController.java
Labels: 🐛 Fix, 📝 Docs, ✨ Feat, 🔧 Chore

#234 test: 엔드포인트 통일로 인한 테스트코드 문제 수정
  monicar-control-center/src/test/java/org/controlcenter/company/presentation/CompanyControllerTest.java
  monicar-control-center/src/test/java/org/controlcenter/notice/presentation/NoticeControllerTest.java
Labels: ✅ Test

#233 chore: cicd 내 redis관련 추가
  .github/workflows/cicd.yml
Labels: 🐛 Fix, priority

#236 fix: cicd 스크립트 수정
  .github/workflows/cicd.yml
  .gitignore
  monicar-control-center/src/main/java/org/controlcenter/config/PropertyConfig.java
  monicar-control-center/src/main/resources/application-prod.yml
  monicar-control-center/src/main/resources/application.yml
Labels: 🔧 Chore

#237 fix: prod 설정 파일 프로필 추가
  monicar-control-center/src/main/resources/application-prod.yml
Labels: 🔧 Chore
